name: Build Android Kernel

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUT_DIR: ${{ github.workspace }}/out
      TOOLCHAIN_DIR: ${{ github.workspace }}/toolchain
      KBUILD_BUILD_USER: Braaed
      KBUILD_BUILD_HOST: github-actions
      KBUILD_BUILD_VERSION: 1
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y \
          build-essential bc bison flex aria2 \
          libelf-dev \
          xz-utils \
          git curl \
          python3 \
          zip unzip  \

    - name: Setup Greenforce Toolchain & AOSP GCC
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$TOOLCHAIN_DIR"
        cd "$TOOLCHAIN_DIR"
        download_gcc() {
            local name="$1"
            local url="$2"

            echo "==> Downloading ${name}..."

            mkdir -p "$TOOLCHAIN_DIR/$name"

            aria2c \
                -x16 \
                -s16 \
                -k1M \
                --file-allocation=none \
                --summary-interval=0 \
                --console-log-level=warn \
                -d "$TOOLCHAIN_DIR" \
                -o "${name}.tar.gz" \
                "$url"

            tar -xzf \
                "$TOOLCHAIN_DIR/${name}.tar.gz" \
                -C "$TOOLCHAIN_DIR/$name"

            rm -f "$TOOLCHAIN_DIR/${name}.tar.gz"
        }
        download_gcc \
          "gcc-arm64" \
          "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android-msm-redbull-4.19-android14-qpr3.tar.gz"

        download_gcc \
          "gcc-arm32" \
          "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android-msm-redbull-4.19-android14-qpr3.tar.gz"

        bash <(wget -qO- https://raw.githubusercontent.com/greenforce-project/greenforce_clang/refs/heads/main/get_clang.sh)

    - name: Setup KernelSUxx
      shell: bash
      run: |
        curl -LSs https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh | bash -s master

    - name: Setup Defconfig
      shell: bash
      run: |
        set -euo pipefail

        DEFCONFIG="arch/arm64/configs/vendor/bengal-perf_defconfig"

        CONFIG_LIST=(
            "CONFIG_KSU=y"
            "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y"
            "CONFIG_KSU_THRONE_TRACKER_ALWAYS_THREADED=y"
        )

        [[ -f "$DEFCONFIG" ]] || {
            echo "ERROR: Defconfig not found: $DEFCONFIG"
            exit 1
        }

        set_config() {
            local file="$1"
            local entry="$2"

            entry="${entry#"${entry%%[![:space:]]*}"}"
            entry="${entry%"${entry##*[![:space:]]}"}"

            [[ -z "$entry" || "$entry" == \#* ]] && return

            local key="${entry%%=*}"
            local value="${entry#*=}"

            [[ "$entry" != *=* ]] && value="y"

            echo "-> ${key}=${value}"

            if grep -q "^${key}=" "$file"; then
                sed -i "s|^${key}=.*|${key}=${value}|" "$file"
            elif grep -q "^# ${key} is not set" "$file"; then
                sed -i "s|^# ${key} is not set|${key}=${value}|" "$file"
            else
                printf '%s=%s\n' "$key" "$value" >> "$file"
            fi
        }

        for config in "${CONFIG_LIST[@]}"; do
            set_config "$DEFCONFIG" "$config"
        done

    - name: Build Kernel
      shell: bash
      run: |
        set -euo pipefail
        export PATH="$TOOLCHAIN_DIR/greenforce-clang/bin:$TOOLCHAIN_DIR/gcc-arm64/bin:$TOOLCHAIN_DIR/gcc-arm32/bin:$PATH"
        export ARCH="arm64"
        export SUBARCH="arm64"
        export CROSS_COMPILE=aarch64-linux-android-
        export CROSS_COMPILE_ARM32=arm-linux-androideabi-
        export CC="clang"
        export AR="llvm-ar"
        export NM="llvm-nm"
        export LD="ld.lld"
        export OBJCOPY="llvm-objcopy"
        export OBJDUMP="llvm-objdump"
        export STRIP="llvm-strip"
        mkdir -p "$OUT_DIR"

        make \
          O="$OUT_DIR" \
          LLVM=1 \
          LLVM_IAS=1 \
          vendor/bengal-perf_defconfig 

        make -j$(nproc) \
          O="$OUT_DIR" \
          LLVM=1 \
          LLVM_IAS=1 

    - name: Prepare AnyKernel3 ZIP
      shell: bash
      run: |
        lastcommit=$(git log -n 1 --pretty=format:'%h' | cut -c 1-7)
        ZIPNAME="4.19-greenforce-ksu.${lastcommit}"
        echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV

        git clone https://github.com/Braeed/AnyKernel3.git --depth 1
        
        echo "===== Boot Directory ====="
        find "$OUT_DIR/arch/arm64/boot" -maxdepth 3 -type f | sort

        # Ensure dtb exists
        if [ ! -f "$OUT_DIR/arch/arm64/boot/dtb" ]; then
            echo "boot/dtb not found, using bengal.dtb..."

            cp \
              "$OUT_DIR/arch/arm64/boot/dts/vendor/qcom/bengal.dtb" \
              "$OUT_DIR/arch/arm64/boot/dtb"
        fi
        cp "$OUT_DIR/arch/arm64/boot/Image" AnyKernel3/
        
        rm -rf AnyKernel3/.git AnyKernel3/README.md
        find AnyKernel3 -name "*placeholder*" -delete

    - name: Upload Kernel
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ZIPNAME }}
        path: AnyKernel3/*
        compression-level: 9
